name: ALOM-PROJECT-BE-CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5. Docker 빌드 환경 설정
      - name: Docker setup
        uses: docker/setup-buildx-action@v3

      # 6. DockerHub 로그인
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 7. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/alom-project-back-container:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/alom-project-back-container:cache
          cache-to: type=inline

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD}}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            export PATH=$PATH:/usr/local/bin
            export PW=${{ secrets.SERVER_PASSWORD }}
            BRANCH=${{ github.ref_name }}
            PORT=8080
            CONTAINER_NAME="alom-project-back"
            echo $PW | sudo -S docker pull ${{ secrets.DOCKERHUB_USERNAME }}/alom-project-back-container:latest
            echo $PW | sudo -S docker stop $CONTAINER_NAME || true
            echo $PW | sudo -S docker rm $CONTAINER_NAME || true
            echo $PW | sudo -S docker run -d -p ${PORT}:8080 --name $CONTAINER_NAME \
              -e TZ=Asia/Seoul \
              -v /etc/localtime:/etc/localtime:ro \
              ${{ secrets.DOCKERHUB_USERNAME }}/alom-project-back-container:latest
